### ISSUE TITLE
Broken Online Documentation URL

### ISSUE THREAD

**Issue by nickkohrn** [danielsaidi/BadgeIcon#1]
The online documentation URL in `README.md` is broken.

<img width="1338" alt="Screenshot 2023-12-20 at 9 25 32 AM" src="https://github.com/danielsaidi/BadgeIcon/assets/5864877/42b71cdb-fbf1-4d17-ad04-52c512453d65">

**Comment by danielsaidi** [comment]
Hi @nickkohrn 

Thank you for noticing! I had an invalid .gitignore file in the repo, so the documentation folder was not pushed 🙈

**Comment by nickkohrn** [comment]
Thanks for creating this package. It makes customizing symbols and maintaining a consistent theme throughout the app simple.

**Comment by danielsaidi** [comment]
Happy you like it! Just let me know if you have some icon suggestions 👍
