### ISSUE TITLE
Rotated SFSymbols or Custom images

### ISSUE THREAD

**Issue by JTostitos** [danielsaidi/BadgeIcon#3]
It would be awesome if I could rotate the SFSymbol I use. Similar to the Ant icons rotation in the image. But instead of it being hardcoded, the user could enter the rotation amount via the initializer for BadgeIcon.

![a42f9658a8254d09](https://github.com/danielsaidi/BadgeIcon/assets/17661536/56b1964a-3510-4764-9c71-381763efe204)

**Comment by danielsaidi** [comment]
Hi @JTostitos 

I used to have this, but removed it when I made the icon Image only, instead of custom view.

I'll see if I can re-add it in a clean way.

**Comment by danielsaidi** [comment]
Hi again,

BadgeIcon `0.5` adds supports for generic icon views. 👍
